### ISSUE TITLE
Creating an API

### ISSUE THREAD

**Issue by galaipa** [jyhsu2000/BannerMaker#1]
Hi!
I have started creating the API. The basic structure is done. By now the only feature is to open the BannerMaker menu. I want to add more functions, like bypassing the paying. 

Don't know why but the fork button is not working at the moment so I can't upload the code. In the pastebin you have the class where al the API voids are stored. The current code is tested and it works OK. To add new functions you just have to add voids there.

I will upload the other classes as soon as I can.

API class: http://pastebin.com/e9pGcXCh

**Comment by jyhsu2000** [comment]
Is there any example of how a plugin using this API?

And is it just a development API? (need include or shade in plugin jar)
Or we can use it as a dependency plugin and use it?

**Comment by jyhsu2000** [comment]
This issue is closed because it has been inactive for a long time.
If still need a discussion of the same issue, please use issue template to create another issue.
