### ISSUE TITLE
Creeper Head Banners not working

### ISSUE THREAD

**Issue by Echyyy** [jyhsu2000/BannerMaker#10]
Every time I try and make a banner featuring a creeper head or my players do, this doesn't work and the craft recipe won't even come up or anything.

- OS: I use a mac? But i have my server via McProHosting
- Java version: Latest
- Server version: Latest
- Minecraft version: 1.13
- BannerMaker version: Latest

I expected to be able to create a banner.

### Actual Behaviour

Every time I try and make a banner featuring a creeper head or my players do, this doesn't work and the craft recipe won't even come up or anything.

### Steps to reproduce

Simply create a creeper banner.

**Comment by jyhsu2000** [comment]
Fixed in 2af1ae038467f991e3b77657c91dbf3ef39a302f

**Comment by Echyyy** [comment]
So do I need to re download the plugin or will this automatically apply to the version I have? Sorry I’m new to this.

**Comment by jyhsu2000** [comment]
You need to re-download it because there is no auto-updater in the plugin.

I will release the new version `2.1.1` soon.
Or you can directly download the snapshot from our [Jenkins](https://ci.kid7.club/job/BannerMaker/).

**Comment by Echyyy** [comment]
Okay, could you provide the link for the download of the update that will fix this please? 

Amazing fast response, I will be reviewing this plugin tonight!

**Comment by jyhsu2000** [comment]
You can always get it from [Jenkins](https://ci.kid7.club/job/BannerMaker/).
Now it's also on [Spigot](https://www.spigotmc.org/resources/bannermaker.4380/) and [GitHub release page](https://github.com/jyhsu2000/BannerMaker/releases).
And it will be available on [BukkitDev](https://dev.bukkit.org/projects/bannermaker) after reviewing by the Bukkit staff.
