### ISSUE TITLE
BannerMaker GUI needs to be updated with Black Dye instead of Ink Sac.

### ISSUE THREAD

**Issue by mibby** [jyhsu2000/BannerMaker#12]
Paper dev (Spigot 1.14.4)
BannerMaker dev 224

The BannerMaker GUI is showing ink sacs instead of black dye in 1.14 for the recipe. This is no longer a thing in 1.14 and people should be using black dye instead.

**Comment by jyhsu2000** [comment]
Thanks for reminder.
I just noticed that after seeing this issue.
I'll fix it.
