### ISSUE TITLE
Delete button missing from "Banner Info" page.

### ISSUE THREAD

**Issue by DarkErminia** [jyhsu2000/BannerMaker#13]
Hello, my version of Bannermaker does not have the delete button on the "Banner Info" page.

Can you fix this, or am I using an old version and it was fixed in the new version?

Thanks,
-Dark.

Image of issue:
https://media.discordapp.net/attachments/588674557242638347/790371001250086932/unknown.png

**Comment by jyhsu2000** [comment]
It have been fixed in **4cca5b64f5ceea02f5bf92f37afb75c0b86a5100**
Make sure you are using version 2.3.1 or newer version.

Hint,
providing version number or build number more helpful than saying `my version`.
