### ISSUE TITLE
BannerMaker is missing the patterns Globe & Snout

### ISSUE THREAD

**Issue by mibby** [jyhsu2000/BannerMaker#14]
https://github.com/jyhsu2000/BannerMaker/blob/94968c14899fa962c65b56813e6b21a663d213dd/src/main/java/club/kid7/bannermaker/util/BannerUtil.java#L175

@jyhsu2000 BannerMaker is missing the patterns Globe ``globe_banner_pattern`` & Snout ``piglin_banner_pattern``.
https://minecraft.fandom.com/wiki/Banner_Pattern

**Comment by jyhsu2000** [comment]
I checked up the wiki page and found these patterns can only be added by using looms.
The current version of BannerMaker only supports crafting table recipes.
I'll make an update for supporting loom recipe these weeks.
Thanks for pointing that out.

**Comment by jyhsu2000** [comment]
I just made an update for this.
Could you take a try at latest version?

Details: https://ci.kid7.club/job/BannerMaker/ (Finished in [build-232](https://ci.kid7.club/job/BannerMaker/232/) and [build-235](https://ci.kid7.club/job/BannerMaker/235/))
Download: https://ci.kid7.club/job/BannerMaker/lastSuccessfulBuild/artifact/target/BannerMaker.jar
