### ISSUE TITLE
Missing banner pattern

### ISSUE THREAD

**Issue by ghost** [jyhsu2000/BannerMaker#19]
Would it be possible to add the 'Snout' banner pattern?

**Comment by jyhsu2000** [comment]
Already added in 8c43e4708ee0856d5a1ac145dc960e2013c2df73
And it still exists in current version

![image](https://user-images.githubusercontent.com/6276648/159832521-d57660f4-5a39-4e00-81be-727c8054ca45.png)
![image](https://user-images.githubusercontent.com/6276648/159832532-8e23ff87-ae36-4cf1-98b8-40e95285eb4f.png)

**Comment by ghost** [comment]
Ah i see, thanks!
