### ISSUE TITLE
RGB message support

### ISSUE THREAD

**Issue by pjindras** [jyhsu2000/BannerMaker#23]
Hello, I would like to ask, if rgb colours are supported in plugins messages.
For example, I tryed prefix: #6a0958&lF#73084f&lé#7b0746&ln#84063e&li#8d0535&lx#96052c&lC#9e0423&lr#a7031a&la#b00212&lf#b80109&lt

But in this format, it couldnt take the colour.

Thank you.

**Comment by jyhsu2000** [comment]
If you want to color message text,
you can use [Formatting codes](https://minecraft.fandom.com/wiki/Formatting_codes) with the prefix "`&`".
e.g. "`&c`" represent red

There is no support for RGB text color in this plugin.
I think string parsing and transformation will be a little complex, so it is not in the plan yet.
If there is a corresponding API in Spigot API, please let me know and it will be evaluated.

**Comment by jyhsu2000** [comment]
As supplementary information,
Spigot (1.16+ as I know) now support using `§x` for RGB colored text.
As other formatting color, you can use prefix `&` (or just use `§` directly) in language files.

`§x§1§2§3§4§5§6` and `&x&1&2&3&4&5&6` represent HEX color `#123456`

More complex example for setting colorful prefix,
```yaml
general:
  prefix: '&6[&x&F&F&0&0&0&0B&x&F&F&2&2&0&0a&x&F&F&4&4&0&0n&x&F&F&6&6&0&0n&x&F&F&8&8&0&0e&x&F&F&A&A&0&0r&x&F&F&C&C&0&0M&x&F&F&E&E&0&0a&x&F&F&F&F&0&0k&x&D&D&F&F&0&0e&x&B&B&F&F&0&0r&6]&r '
```
![image](https://github.com/jyhsu2000/BannerMaker/assets/6276648/2f1c442d-ee49-4f3b-ab49-17116c7f4277)
