### ISSUE TITLE
Broken on 1.21

### ISSUE THREAD

**Issue by ShadowTigerCool** [jyhsu2000/BannerMaker#27]
### Environment
- OS: CentOS 8 Stream / Rocky Linux 8
- Java version: 21.03
- Server version: 1.21-62-master@5a503d7)
- Minecraft version: 1.21
- BannerMaker version: 2.4.0

### Expected Behaviour

-  Menu Would work, but giving me an "Could not pass event InventoryClickEvent to BannerMaker v2.4.0" error 

### Actual Behaviour

-  https://mcpaste.io/23a6f343813d0fc6

### Steps to reproduce

1. /bm
2. create banner
3. selecting a banner

**Comment by jyhsu2000** [comment]
Fixed in d9e4c255d8ce176391d12305e52ddbf939e1af79
Please take a try on [this snapshot version of BannerMaker.jar](https://github.com/jyhsu2000/BannerMaker/actions/runs/9921163462/artifacts/1698132590)

**Comment by SynergyShadow** [comment]
It's working, Thanks for the quick response 👍
