### ISSUE TITLE
1.13.1 API Compatibility

### ISSUE THREAD

**Issue by mibby** [jyhsu2000/BannerMaker#8]
Any plans on updating to support Spigot 1.13 API? :)

**Comment by jyhsu2000** [comment]
Yes.
But I'm busy in these weeks.
Maybe in a couple of days.

I just updated a version for `1.13.*`. (tested on 1.13.1)
Take a try: [#201](https://ci.kid7.club/job/BannerMaker/201/)
Please note that, **this build is for `1.13.*` only**.

There are some incompatible API changes in 1.13.
I will take times to fix for compatibility.
I'll release next version after that.

If still something wrong in this build,
please **follow the template** to open another issue.
